djangoshop/djangoshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('eshopapp.urls')),
    url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoshop/eshopapp/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from eshopapp.views import (
        base_view, 
        category_view, 
        product_view, 
        cart_view, 
        add_to_cart_view, 
        remove_from_cart_view, 
        change_item_qty_view, 
        checkout_view,
        order_create_view,
        make_order_view,
        account_view,
        registration_view,
        login_view,
        notify_create,
        notify_delete
        )

urlpatterns = [
    url(r'^category/(?P<category_slug>[-\w]+)/$', category_view, name='category_detail'),
    url(r'^product/(?P<product_slug>[-\w]+)/$', product_view, name='product_detail'),
    url(r'^add_to_cart/$', add_to_cart_view, name='add_to_cart'),
    url(r'^remove_from_cart_view/$', remove_from_cart_view, name='remove_from_cart'),
    url(r'^change_item_qty/$', change_item_qty_view, name='change_item_qty'),
    url(r'^cart/$', cart_view, name='cart'),
    url(r'^checkout/$', checkout_view, name='checkout'),
    url(r'^order/$', order_create_view, name='create_order'),
    url(r'^make_order/$', make_order_view, name='make_order'),
    url(r'^thank_you/$', TemplateView.as_view(template_name='thank_you.html'), name='thank_you'),
    url(r'^account/$', account_view, name='account'),
    url(r'^registration/$', registration_view, name='registration'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('base')), name='logout'),
    url(r'^notify_create/$', notify_create, name='notify_create'),
    url(r'^notify_delete/$', notify_delete, name='notify_delete'),
    url(r'^$', base_view, name='base'),
]

djangoshop/eshopapp/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify
from transliterate import translit  
from notifications.signals import notify
from decimal import Decimal

class Category(models.Model):

    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_slug': self.slug})

def pre_save_category_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(instance.name, reversed=True))
        instance.slug = slug

pre_save.connect(pre_save_category_slug, sender=Category)


class Brand(models.Model):

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return '{0}/{1}'.format(instance.slug, filename)


class Product(models.Model):

    category = models.ForeignKey(Category)
    brand = models.ForeignKey(Brand)
    title = models.CharField(max_length=120)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to=image_folder)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_slug': self.slug})

def product_available_notification(sender, instance, *args, **kwargs):
    if instance.available:
        avait_for_notification = [notification for notification in MiddlwareNotification.objects.filter(
            product = instance)]
        for notification in avait_for_notification:
            notify.send(instance,
                    recipient=[notification.user_name],
                    verb='Уважаемый {0}! {1}, который Вы ждете, поступил'.format(
                        notification.user_name.username,
                        instance.title),
                    description=instance.slug
                    )
            notification.delete()

post_save.connect(product_available_notification, sender=Product)


class CartItem(models.Model):

    product = models.ForeignKey(Product, blank=True)
    qty = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return 'Cart item for product {}'.format(self.product.title)


class Cart(models.Model):
    
    items = models.ManyToManyField(CartItem)
    cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.id) 

    def add_to_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        new_item = CartItem.objects.create(product=product, item_total=product.price)
        if new_item not in cart.items.all():
            cart.items.add(new_item)
            cart.save()
    
    def remove_from_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        for cart_item in cart.items.all():
            if cart_item.product == product:
                cart.items.remove(cart_item)
                cart.save()
        
    def change_qty(self, qty, item_id):
        cart = self
        cart_item = CartItem.objects.get(id=int(item_id))
        cart_item.qty = int(qty)
        cart_item.item_total = cart_item.qty * Decimal(cart_item.product.price)
        cart_item.save()
        new_cart_total = 0.00
        for item in cart.items.all():
            new_cart_total += float(item.item_total)
        cart.cart_total = new_cart_total
        cart.save()


ORDER_STATUS_CHOICES = (
	('Принят в обработку', 'Принят в обработку'),
	('Выполняется', 'Выполняется'),
	('Оплачен', 'Оплачен')
)

class Order(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    items = models.OneToOneField(Cart)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    buying_type = models.CharField(max_length=40, choices=(('Самовывоз', 'Самовывоз'), 
            ('Доставка', 'Доставка')), default='Самовывоз')
    date = models.DateTimeField(auto_now_add=True)
    delivery_date = models.DateField()
    comments = models.TextField()
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0])

    def __str__(self):
        return "Заказ №{0}".format(str(self.id))


class MiddlwareNotification(models.Model):
    user_name = models.ForeignKey(settings.AUTH_USER_MODEL)
    product = models.ForeignKey(Product)
    is_notified = models.BooleanField(default=False)

    def __str__(self):
        return "Нотификация для пользователя {0} о поступлении товара {1}".format(
            self.user_name.username,
            self.product.title
        )

djangoshop/eshopapp/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth import login, authenticate
from eshopapp.models import Category, Product, CartItem, Cart, Order, MiddlwareNotification
from eshopapp.forms import OrderForm, RegistrationForm, LoginForm
from notifications.models import Notification


def base_view(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart.objects.create()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
            'categories': categories,
            'products': products,
            'cart': cart
    }
    return render(request, 'base.html', context) 


def product_view(request, product_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart.objects.create()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product = Product.objects.get(slug=product_slug)
    categories = Category.objects.all()
    check_for_subscribe = [notification.product for notification in MiddlwareNotification.objects.filter(
        user_name = request.user,
        product = product
        )]
    context = {
        'product': product,
        'categories': categories,
        'cart': cart,
        'check_for_subscribe': check_for_subscribe
    }
    return render(request, 'product.html', context)


def category_view(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    products_of_category = Product.objects.filter(category=category)
    categories = Category.objects.all()
    context = {
        'category': category,
        'products_of_category': products_of_category,
        'categories': categories
    }
    return render(request, 'category.html', context)


def cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart.objects.create()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    context = {
        'cart': cart,
        'categories': categories
    }
    return render(request, 'cart.html', context)


def add_to_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart.objects.create()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    cart.add_to_cart(product_slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({
        'cart_total': cart.items.count(),
        'cart_total_price': cart.cart_total
    })

def remove_from_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart.objects.create()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    cart.remove_from_cart(product_slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({
        'cart_total': cart.items.count(),
        'cart_total_price': cart.cart_total
    })


def change_item_qty_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart.objects.create()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    qty = request.GET.get('qty')
    item_id = request.GET.get('item_id')
    cart.change_qty(qty, item_id)
    cart_item = CartItem.objects.get(id=int(item_id))
    return JsonResponse({
        'cart_total': cart.items.count(),
        'item_total': cart_item.item_total,
        'cart_total_price': cart.cart_total
    })


def checkout_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart.objects.create()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    context = {
        'cart': cart,
        'categories': categories
    }
    return render(request, 'checkout.html', context)


def order_create_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart.objects.create()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    form = OrderForm(request.POST or None)
    context = {
        'form': form,
        'categories': categories
    }
    return render(request, 'order.html', context)


def make_order_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart.objects.create()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    categories = Category.objects.all()
    if form.is_valid():
        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']
        phone = form.cleaned_data['phone']
        buying_type = form.cleaned_data['buying_type']
        address = form.cleaned_data['address']
        delivery_date = form.cleaned_data['delivery_date']
        comments = form.cleaned_data['comments']
        new_order = Order.objects.create(
            user=request.user,
            items=cart,
            total=cart.cart_total,
            first_name=name,
            last_name=last_name,
            phone=phone,
            address=address,
            delivery_date=delivery_date,
            buying_type=buying_type,
            comments=comments
        )
        del request.session['cart_id']
        del request.session['total']
        return HttpResponseRedirect(reverse('thank_you'))
    context = {
        'form': form,
        'categories': categories
    }
    return render(request, 'order.html', context)


def account_view(request):
    orders = Order.objects.filter(user=request.user).order_by('-id')
    categories = Category.objects.all()
    context = {
        'orders': orders,
        'categories': categories
    }
    return render(request, 'account.html', context)


def registration_view(request):
    form = RegistrationForm(request.POST or None)
    if form.is_valid():
        new_user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        email = form.cleaned_data['email']
        new_user.username = username
        new_user.set_password(password)
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.email = email
        new_user.save()
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    categories = Category.objects.all()
    context = { 
        'form': form,
        'categories': categories
    }
    return render(request, 'registration.html', context)


def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    categories = Category.objects.all()
    context = {
        'form': form,
        'categories': categories
    }
    return render(request, 'login.html', context)


def notify_create(request):
    product_slug = request.GET.get('product_slug')
    new_notification = MiddlwareNotification.objects.create(
            user_name = request.user,
            product = Product.objects.get(slug=product_slug)
            )
    return JsonResponse({'created': 'Вы подписались на уведомления о поступлении. Как только товар появится, мы Вам сообщим'})


def notify_delete(request):
    slug = request.GET.get('slug')
    notification_on_delete = Notification.objects.get(recipient=request.user, description=slug)
    notification_on_delete.delete()
    return JsonResponse({'ok': 'ok'})

djangoshop/eshopapp/templates/account.html
{% extends 'base.html' %}

{% block content %}


<h3 class="text-center">Личный кабинет пользователя {{ request.user }}</h3>
<hr>
<h4 class='text-center'>Ваши заказы</h4>
<table class='table'>
<tr style='background:lightblue;'>
	<td class='text-center'>Номер заказа</td>
	<td class='text-center'>Дата заказа</td>
	<td class='text-center'>Статус заказа</td>
	<td class='text-center'>Стоимость заказа</td>
	<td class='text-center'>Детали заказа</td>
	<td></td>
</tr>
{% for order in orders %}
<tr>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ order.id }}</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ order.date }}</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ order.status }}</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ order.total }} руб.</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'><button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal-{{ order.id }}">
  Детали заказа
</button></td>
</tr>
{% endfor %}
</table>

<!-- Modal -->
{% for order in orders %}
<div class="modal fade" id="myModal-{{ order.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Заказ № {{ order.id  }}</h4>
      </div>
      <div class="modal-body">
          <h3>Товар</h3>
          <table class='table'>
              {% for item in order.items.items.all %}
              <tr>
                  <td>{{ item.product.title }}</td>
                  <td>{{ item.qty }} шт.</td>
                  <td>{{ item.item_total }} руб.</td>
                  <td>{{ item.id }}</td>
              </tr>
              {% endfor %}
              <tr>
                  <td></td>
                  <td>Итого:</td>
                  <td>{{ order.items.cart_total }} руб.</td>
              </tr>
          </table>
          <h3>Заказчик</h3>
          <p>Имя: {{ order.first_name }} </p>
          <p>Фамилия: {{ order.last_name }} </p>
          <p>Телефон: {{ order.phone }} </p>
          <h3>Тип доставки</h3>
          <p>{% if order.buying_type == 'self' %}Самовывоз{% else %}Доставка{% endif %}</p>
          <p>{% if order.buying_type == 'delivery' %}Адрес: {{ order.address }}{% endif %}</p>
          <h3>Комментарий</h3>
          <p>{{ order.comments }} </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}

djangoshop/eshopapp/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h3 class='text-center'>Ваша корзина</h3>
<br>
{% if cart.items.count > 0 %}
<div class='my-cart'>
    <table class='table'>
        <tr>
            <td class='text-center'><strong>Товар</strong></td>
            <td class='text-center'><strong>Кол-во</strong></td>
            <td class='text-center'><strong>Цена</strong></td>
            <td class='text-center'></td>
        </tr>
        {% for item in cart.items.all %}
        <tr class='cart-item-{{ item.product.id }}'>
            <td class='text-center'>{{ item.product.title }}</td>
            <td class="text-center">
                <form action='' method='GET'>
                    <input type='number' name='qty' class='cart-item-qty' data-id='{{ item.id }}' value='{{ item.qty }}' min='1' style='width: 50px;'>
                </form>
            </td>
            <td class='text-center' id='cart-item-total-{{ item.id }}'>{{ item.item_total }} руб.</td>
            <td class='text-center'><a href='#' class='remove_from_cart' data-slug='{{ item.product.slug }}' data-id='{{ item.product.id }}'><button class='btn btn-default'>Удалить из корзины</button></a></td>
        </tr>
        {% endfor %}
        <tr>
            <td></td>
            <td class='text-center'> <strong>Итого: </strong></td>
            <td class='text-center' id='cart-total-price'><strong>{{ cart.cart_total }} руб.</strong></td>
            <td class='text-center'></td>
        </tr>
    </table>
    <a href='{% url 'checkout' %}' class='pull-right'><button class='btn btn-info'>Предварительный заказ</button></a>
</div>
<h3 class='cart-empty'></h3>
{% else %}
<h3 class='text-center'>Ваша корзина пуста</h3>
{% endif %}

<script src='{% static "js/jquery.js" %}'></script>
<script>
$(document).ready(function(){
    $('.cart-empty').css('display', 'none')
	$('.remove_from_cart').on('click', function(e){
		e.preventDefault()
		product_slug = $(this).attr('data-slug')
        item_product_id = $(this).attr('data-id')
		data = {
			product_slug: product_slug
		}
		$.ajax({
			type: "GET",
			url: '{% url "remove_from_cart" %}',
			data: data,
			success: function(data){
				$("#cart_count").html(data.cart_total)
                $(".cart-item-"+item_product_id).css('display', 'none')
                $('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(2) + ' руб. </strong>')
                if (parseInt(data.cart_total) == 0){
                    $('.my-cart').css('display', 'none')
                    $('.cart-empty').css('display', 'block')
                    $('.cart-empty').html('<h3 class="text-center">Ваша корзина пуста</h3>')
                }
			}
		})
	})
})

$(document).ready(function(){
    $('.cart-item-qty').on('click', function(e){
        item_id = $(this).attr('data-id')
        qty = $(this).val()
        data = {
            item_id: item_id,
            qty: qty
        }
        $.ajax({
            type: "GET",
            url:'{% url 'change_item_qty' %}',
            data: data,
            success: function(data){
                $('#cart-item-total-'+item_id).html(parseFloat(data.item_total).toFixed(2) + ' руб.')
                $('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(2) + ' руб. </strong>')
            }
        })
    })
})
</script>
{% endblock content %}

djangoshop/eshopapp/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class='col-sm-12'>
<h2>{{ category.name }}</h2>
<br>
{% for product in products_of_category %}
<div class='col-sm-4'>
    <a href='{{ product.get_absolute_url }}'><img src='{{ product.image.url }}' style='width: 100%; height: 300px;'></a>
<h4 class='text-center'>{{ product.title }}</h4>
<p class='text-center'>Цена: <strong>{{ product.price }}</strong></p>
{% if request.user.is_authenticated %}<p class='text-center'><a href='#' class='add_to_cart' data-slug='{{ product.slug }}'><button class='btn btn-danger'>Добавить в корзину</button></a></p>{% endif %}
<br><br>
{% if not request.user.is_authenticated %}<p class='text-center'>Заказывать товар могут только авторизированные пользователи. Пожалуйста, <a href='{% url 'login' %}'>войдите</a> или <a href='{% url 'registration' %}'>зарегистрируйтесь</a></p>{% endif %}
</div>
{% endfor %}
</div>
<script src='{% static "js/jquery.js" %}'></script>
<script>
$(document).ready(function(){
	$('.add_to_cart').on('click', function(e){
		e.preventDefault()
		product_slug = $(this).attr('data-slug')
		data = {
			product_slug: product_slug
		}
		$.ajax({
			type: "GET",
			url: '{% url "add_to_cart" %}',
			data: data,
			success: function(data){
				$("#cart_count").html(data.cart_total)
			}
		})
	})
})
</script>
{% endblock content %}

djangoshop/eshopapp/templates/checkout.html
{% extends 'base.html' %}

{% block content %}

<h3 class='text-center'>Предварительный заказ</h3>
<br>
<table class='table'>
    <tr>
        <td class='text-center'><strong>Товар</strong></td>
        <td class='text-center'><strong>Кол-во</strong></td>
        <td class='text-center'><strong>Цена</strong></td>
        <td class='text-center'></td>
    </tr>
    {% for item in cart.items.all %}
    <tr>
        <td class='text-center'>{{ item.product.title }}</td>
        <td class="text-center">{{ item.qty }}</td>
        <td class='text-center'>{{ item.item_total }} руб.</td>
        <td class='text-center'></td>
    </tr>
    {% endfor %}
    <tr>
        <td></td>
        <td class='text-center'> <strong>Итого: </strong></td>
        <td class='text-center'><strong>{{ cart.cart_total }} руб.</strong></td>
        <td class='text-center'></td>
    </tr>
</table>
<a href='{% url 'create_order' %}' class='pull-right'><button class='btn btn-info'>Оформить заказ</button></a>

{% endblock content %}

djangoshop/eshopapp/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content%}
<h3 class='text-center'>Авторизация</h3>
<div class='col-sm-8 col-sm-offset-2'>
<hr>
<form action='' method="POST">
	{% csrf_token %}
	{{ form|crispy }}
	<input type='submit' class='btn btn-success btn-block' value='Войти'>
</form>
</div>
{% endblock content %}

djangoshop/eshopapp/templates/order.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class='text-center'>Оформление заказа</h3>
<hr>
<form action='{% url 'make_order' %}' method="POST">
{% csrf_token %}
<div class='col-sm-4'>
	{{ form.name|as_crispy_field }}
</div>
<div class='col-sm-4'>
	{{ form.last_name|as_crispy_field }}
</div>
<div class='col-sm-4'>
	{{ form.phone|as_crispy_field }}
</div>
    {{ form.buying_type|as_crispy_field }}
    {{ form.address|as_crispy_field }}
    {{ form.delivery_date|as_crispy_field }}
    {{ form.comments|as_crispy_field }}
    <input type='submit' class='btn btn-success' value='Оформить заказ'>
</form>
<script src="{% static 'js/jquery.js' %}"></script>
<script>
	$(document).ready(function(){
		$('#div_id_address').css('display', 'none')
		$('#id_buying_type').on('click', function(){
			buying_type = $(this).val()
			if(buying_type == 'delivery'){
				$('#div_id_address').css('display', 'block')
			}else{
				$('#div_id_address').css('display', 'none')
			}
		})
		$('#id_delivery_date_month').css('width', '100px')
		$('#id_delivery_date_month').css('display', 'inline')
		$('#id_delivery_date_year').css('width', '100px')
		$('#id_delivery_date_year').css('display', 'inline')
		$('#id_delivery_date_day').css('width', '70px')
		$('#id_delivery_date_day').css('display', 'inline')
	})
</script>
{% endblock content %}

djangoshop/eshopapp/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content%}
<h3 class='text-center'>Регистрация нового пользователя</h3>
<div class='col-sm-8 col-sm-offset-2'>
<hr>
<form action='' method="POST">
	{% csrf_token %}
	{{ form|crispy }}
	<input type='submit' class='btn btn-success btn-block' value='Зарегистрироваться'>
</form>
</div>
{% endblock content %}

djangoshop/eshopapp/templates/thank_you.html
{% extends 'base.html' %}


{% block content %}

<div class='col-sm-8 col-sm-offset-2'>
	<h3 class='text-center'>Спасибо за Ваш заказ! Он принят в обработку. В ближайшее время менеджер с Вами свяжется</h3>
	<p class='text-center'><a href='/'><button class='btn btn-default'>Вернуться в покупкам</button></a></p>
</div>

{% endblock content %}